# Generated by Django 3.2.12 on 2022-04-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='specialization',
            new_name='major',
        ),
    ]
