# Generated by Django 3.2.12 on 2022-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_rename_specialization_user_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
